[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
via_ir = true
fs_permissions = [{ access = "read", path = "./"}]

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "short"
quote_style = "double"

# perfis opcionais
[profile.ci]
optimizer_runs = 200
